import sqlite3

libros_data = [
    ('a libero nam dui proin leo odio porttitor id consequat', 'Irvine Rasher', '342996977-8', True),
    ('ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula', 'Gardner Daley', '292406744-8', True),
    ('amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus', 'Grata Gaize', '715161516-7', False),
    ('pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis', 'Storm Quincey', '386243263-7', False),
    ('pretium iaculis justo in hac habitasse platea dictumst etiam faucibus', 'Benoit Nisuis', '395384962-X', False),
    ('nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat', 'Lukas Gaythor', '783560732-8', True),
    ('placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris', 'Cassandra Raoul', '821875236-6', True),
    ('elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla', 'Wendy Santer', '859085215-6', True),
    ('eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 'Mufinella Chapple', '020518520-7', False),
    ('nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in', 'Lolita Foan', '966289407-1', False),
    ('amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam', 'Gordie Izakof', '691072928-5', False),
    ('accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 'Willi Imbrey', '622774475-1', True),
    ('eu felis fusce posuere felis sed lacus morbi sem mauris laoreet', 'Alexio Crowter', '085903539-5', False),
    ('auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum', 'Rem Schwerin', '178867793-5', False),
    ('non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu', 'Ursuline Cheney', '860967634-X', False),
    ('nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 'Dag Kingdon', '770211011-2', False),
    ('convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien', 'Betsy Deverill', '292935370-8', True),
    ('luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum', 'Hermina McFater', '838802570-8', False),
    ('vestibulum sit amet cursus id turpis integer aliquet massa id', 'Gilberto Finnick', '469574724-3', False),
    ('sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis', 'Christian Torricella', '523220575-7', True),
    ('dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est', 'Ranice Morgen', '026630534-2', False),
    ('libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a', 'Darren MacConnechie', '964381555-2', True),
    ('ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi', 'Arther Mockford', '791615188-X', True),
    ('vestibulum vestibulum ante ipsum primis in faucibus orci luctus et', 'Ragnar O\'Shevlin', '116946483-1', True),
    ('nec dui luctus rutrum nulla tellus in sagittis dui vel', 'Reg Avraham', '767972139-4', False),
    ('vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante', 'Ethyl Anfrey', '224408325-X', True),
    ('sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur', 'Pincus Haston', '119512073-7', False),
    ('at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi', 'Karisa Brockbank', '486949467-1', True),
    ('vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet eleifend pede', 'Amalle Thrift', '046391469-4', False),
    ('egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', 'Marris Jenk', '248674964-0', False),
    ('posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus', 'Filmore Keeney', '357438060-7', False),
    ('semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et', 'Gib Le - Count', '180463777-7', False),
    ('aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis', 'Blythe Glave', '414672200-4', True),
    ('sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 'Irina Mote', '326539232-5', True),
    ('interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', 'Kala Chugg', '585097656-6', True),
    ('consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante', 'Karil Kinset', '081107252-5', True),
    ('non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim', 'Jerry Chimenti', '264446937-6', True),
    ('magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac', 'Dru Baldcock', '346399792-4', True),
    ('aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 'Nannette Dubock', '756849816-6', False),
    ('justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam pharetra magna', 'Marius Kleinzweig', '880230720-2', True),
    ('ut odio cras mi pede malesuada in imperdiet et commodo', 'Marv Powder', '488428738-X', False),
    ('metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam', 'Garey Aikett', '603522068-1', False),
    ('id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in', 'Ketty O\'Cosgra', '898281119-2', False),
    ('enim leo rhoncus sed vestibulum sit amet cursus id turpis integer', 'Sophia Whitlock', '342490132-6', False),
    ('dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium', 'Giraldo Swainsbury', '624475259-7', True),
    ('ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 'Francyne Leithgoe', '962435460-X', False),
    ('pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus nulla', 'Catherine Shedd', '617957788-9', False),
    ('vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue', 'Aleda Gatherer', '403597587-7', False),
    ('nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros', 'Trev Iacovone', '692039241-0', True),
    ('ultrices mattis odio donec vitae nisi nam ultrices libero non', 'Gordy Ruslinge', '531358945-8', True),
    ('platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum', 'Loraine Littefair', '884643488-9', False),
    ('lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac habitasse', 'Erma Hurrell', '045722207-7', False),
    ('sed ante vivamus tortor duis mattis egestas metus aenean fermentum', 'Celka Pickthorn', '815820423-6', True),
    ('in est risus auctor sed tristique in tempus sit amet sem', 'Anne-corinne Kinsell', '016014779-4', False),
    ('luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis', 'Terri Tows', '327002942-X', False),
    ('in purus eu magna vulputate luctus cum sociis natoque penatibus et magnis dis parturient', 'Chicky Hedden', '695262033-8', False),
    ('porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 'Letty Hartin', '402615239-1', True),
    ('odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer', 'Starr O\'Flaverty', '022658836-X', True),
    ('id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', 'Stormy Kubiczek', '425699849-7', False),
    ('in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum', 'Martelle Melling', '543663317-X', True),
    ('orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', 'Ransell Quinnelly', '068078624-4', True),
    ('in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae', 'Niels Lavallie', '142856052-1', False),
    ('sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut', 'Horatio Feild', '555781593-7', True),
    ('eros viverra eget congue eget semper rutrum nulla nunc purus phasellus in felis donec', 'Curt Crapper', '521712163-7', False),
    ('rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis', 'Ebba Betje', '013606912-6', True),
    ('id massa id nisl venenatis lacinia aenean sit amet justo morbi', 'Bo Lackner', '884653796-3', True),
    ('morbi non quam nec dui luctus rutrum nulla tellus in sagittis dui vel nisl duis', 'Felicity Hanes', '987083407-8', False),
    ('est donec odio justo sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia', 'Ingmar Fesby', '315641464-6', True),
    ('sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 'Aurea McIlwain', '888895217-9', False),
    ('rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis lacinia aenean', 'Annetta Klemt', '124086956-8', False),
    ('pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst', 'Abbie Aronowitz', '770420028-3', True),
    ('maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur', 'Husain Lelliott', '286186318-8', False),
    ('platea dictumst morbi vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien', 'Ilise Artist', '635545153-6', True),
    ('morbi a ipsum integer a nibh in quis justo maecenas rhoncus', 'Shell Staunton', '876141566-9', False),
    ('nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt', 'Gena Ridd', '017414965-4', True),
    ('eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus', 'Winona Gallaccio', '059454646-X', False),
    ('tortor sollicitudin mi sit amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam', 'Jeddy Nestle', '180090561-0', True),
    ('mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu', 'Harmonie Hacket', '201660497-2', True),
    ('ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque', 'Ramona Christofe', '878335393-3', True),
    ('a pede posuere nonummy integer non velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum', 'Glennie Cheyenne', '000712364-7', False),
    ('blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin', 'Roch Kuhnert', '030854007-7', True),
    ('odio donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 'Elwira Comelli', '753917962-7', False),
    ('non pretium quis lectus suspendisse potenti in eleifend quam a odio in hac', 'Anabella Ambroisin', '613427180-2', True),
    ('consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at', 'Cyril Eatttok', '290762851-8', False),
    ('in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis', 'Rolando Bluett', '570400687-6', False),
    ('nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante', 'Benji Glozman', '492321181-4', True),
    ('quisque porta volutpat erat quisque erat eros viverra eget congue eget semper', 'Shae Maple', '545264549-7', False),
    ('pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse potenti cras in', 'Caryl Bellanger', '242089336-0', True),
    ('facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum', 'Henderson Brigshaw', '123573957-0', False),
    ('in consequat ut nulla sed accumsan felis ut at dolor quis odio', 'Wanda Jenson', '310997018-X', False),
    ('est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante', 'Salomone MacLardie', '183677635-7', False),
    ('ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum', 'Ignacio Littler', '088445691-9', False),
    ('nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla', 'Raynell Scramage', '042847911-1', False),
    ('nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', 'Tisha Blissitt', '204365685-6', True),
    ('ac nulla sed vel enim sit amet nunc viverra dapibus nulla suscipit ligula in', 'Mic Circuitt', '534785654-8', True),
    ('ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat', 'Hyatt Kubin', '280998741-6', False),
    ('eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst', 'Rriocard Happer', '139213607-5', False),
    ('ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in', 'Ely Patrone', '060758461-0', True),
    ('sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo', 'Kennith Conkey', '302925791-6', True),
    ('cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat', 'Alane Byrth', '189502222-3', True),
]

with sqlite3.connect('biblioteca.db') as conn:
    c = conn.cursor()
    c.executemany("INSERT OR IGNORE INTO libros (titulo, autor, isbn, disponible) VALUES (?, ?, ?, ?)", libros_data)
    conn.commit()
    c.close()

